### ISSUE TITLE
How to do an early return and keep processing information in the next middleware?

### ISSUE THREAD

**Issue by nitrocode** [koajs/koa#1169]
I have a certain middleware that based on a specific option, it needs to

1. retrieve data from the database in the next middleware
2. log it to a file in the middleware after that

On the client side, the user can and should skip all of that and just get a status 200. How would I go about this in koa? Instead of awaiting the db response and then logging it in the next middleware, is the only solution to NOT await the db response and log the db response within a callback or a thenable function so it doesn't hold the client? or is there a more robust way?

**Comment by fl0w** [comment]
You can't return and also continue - that makes no sense. What you can do is to write manually to socket and then continue the chain by returning next.

This to me isn't a clean solution and does sound like a code smell where the flow of a Koa application is forced into something it wasn't designed for. Instead, since this looks like a background process type deal, I'd either just kick a new promise which I don't await for (remember the handle/catch errors), or ideally have a away to handle background processes through a worker pipeline.

So in pseudo code:
```js
app.use(async ctx => {
  db.fetch() // Assuming a Promise is returned
    .then(() => { ... })
    .catch(err => {
      log(err)
    })

  // status 200 will be returned regardless of if db.fetch() resolves or rejects.
  ctx.status = 200
})
```

**Comment by nitrocode** [comment]
I was thinking along those lines too. Thank you for confirming the pattern.
