### ISSUE TITLE
video stream error

### ISSUE THREAD

**Issue by re1oaded** [koajs/koa#1345]
```javascript
router.get('/mp4/:name', async ctx => {
    let file = './video/' + ctx.params.name;
    let stat = fs.statSync(file);
    let fileSize = stat.size;
    let range = ctx.header.range;
    if (range) {
        let parts = range.replace(/bytes=/, "").split("-");
        let start = parseInt(parts[0], 10);
        let end = parts[1] ? parseInt(parts[1], 10) : fileSize - 1;
        let chunksize = (end - start) + 1;
        ctx.status = 206;
        ctx.set('Content-Range', `bytes ${start}-${end}/${fileSize}`);
        ctx.set('Accept-Ranges', 'bytes');
        ctx.set('Content-Length', chunksize);
        ctx.set('Content-Type', 'video/mp4');
        ctx.body = fs.createReadStream(file, { start, end });
    } else {
        ctx.status = 200;
        ctx.set('Content-Length', fileSize);
        ctx.set('Content-Type', 'video/mp4');
        ctx.body = fs.createReadStream(file);
    }
});
```

I used koa to process the video stream and got an unhandled error. The console always outputs this error whenever my video fast forwards.

```cmd
  Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:111:27)


  Error: write ECANCELED
      at WriteWrap.afterWrite [as oncomplete] (net.js:779:14)


  Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
```

```cmd
Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
```
This error is always output when the video is fast forwarded. Express does not have this error. I want to know how to solve it.

I have been looking for a solution, but still can't solve it, thanks.

**Comment by re1oaded** [comment]
@jonathanong @dead-horse @igoradamenko

**Comment by igoradamenko** [comment]
@re1oaded, hi! As I understand these error are OK, because connection is being resetted when you fast forwarding video on client. And that's the reason why your pipes broke at that moment.

Try to check #1089 or https://github.com/koajs/koa/wiki/Error-Handling, looks like they have a solution (global error handling). It's just an error suppressing, but I'm not sure that you need any other handling here.

**Comment by re1oaded** [comment]
@igoradamenko Thanks, Igor.

Do you mean that these errors will not affect the video playback?

I don't need any other handling for errors unless it affects the normal playback of the video.

Btw, is there any problem with my code?
Opening the video address directly in Firefox cannot be fast forwarded, Chrome is ok.
e.g: http://127.0.0.1/mp4/video.mp4

**Comment by igoradamenko** [comment]
@re1oaded, yes, I think it's a mistake in your code.

According to MDN browser should send HTTP range request (with “Range” header) only when it get “Accept-Ranges” header from the server: https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests. 

As I understand, Chrome always sends “Range” header for video, and you reply to it with stream and “Accept-Ranges” header. But Firefox sends “Range” only when it already got “Accept-Ranges” from the server. So, in Chrome you see correctly working video fast forwarding, but in Firefox it works in a strage way: it loads a chunk in an internal FF buffer, then pauses loading, then when you want to fast forward it loads next chunk. If it's not enough to show you requested position of the video, FF doesn't care and you need to click on progress bar again and again, to force FF to load more chunks.

So, yeah, it doesn't work correctly in FF. The reason is quite simple — due to this chunk-loading algorithm FF can't get “Accept-Ranges” from your server because you send it only when you get “Range” from the browser.

Fix is quite simple — just always set “Accept-Ranges” for videos. I tested it and it works fine in FF now. 

Hope it helps!

**Comment by igoradamenko** [comment]
Oh, and,

> Do you mean that these errors will not affect the video playback?

I think it doesn't affect the playback at all, but I don't have enough experience with these things. However I don't see any errors in this behaviour, it sounds logical.

**Comment by re1oaded** [comment]
Thanks igor. I know what to do, you are a nice guy.

**Comment by igoradamenko** [comment]
@re1oaded, thanks!

In this case, it looks like you can close the issue, doesn't it?
