### ISSUE TITLE
ESLint warning about a race condition when assigning an awaited result to body

### ISSUE THREAD

**Issue by damianobarbati** [koajs/koa#1351]
Hey guys... recent ESLint update warns me about the following (screenshot): any hint about how to solve this?
Because I'm lacking ideas and I'm not sure whether this is valid or not: I may reassign ctx.body later, but given value at that moment is the value I awaited for. Right?

Infos: https://eslint.org/docs/rules/require-atomic-updates

<img width="1039" alt="Screenshot 2019-06-30 at 10 37 11" src="https://user-images.githubusercontent.com/2225869/60394347-29dcaf00-9b23-11e9-9a82-8b35b9475555.png">

**Comment by fl0w** [comment]
The rule (require-atomic-updates) is pretty weird in Koa context because it assumes multiple promises can resolve and assign to ctx.body. In practice, Koa (actually koa-compose) only runs one mw (promise) at a time so this rule is ... weird. I'd turn it off, or at least disable it for ctx.body assignments.

**Comment by stalniy** [comment]
it just assumes that `ctx` is a shared resource but in practice every request creates its own `ctx`
