### ISSUE TITLE
response.remove doesn't seem to work

### ISSUE THREAD

**Issue by paramsinghvc** [koajs/koa#1382]
`response.remove` as the docs say, can be used to remove the header from the response being sent, but it's not removing it as I've tried. `response.set` works though.

```        res.remove("X-Powered-By");```

<img width="234" alt="Screenshot 2019-09-11 at 09 44 18" src="https://user-images.githubusercontent.com/4329912/64667814-c05d1300-d478-11e9-89cb-53e01e5e2411.png">

**Comment by fl0w** [comment]
It works fine according to the following example.

```js
const Koa = require('koa')
const app = new Koa()

app.use(async (ctx, next) => {
  ctx.set('X-Powered-By', 'Express')
  await next()
})

app.use(async (ctx) => {
  ctx.remove('X-Powered-By')
  ctx.body = 'ok'
})

app.listen(3000)
```

```sh
$ curl -v localhost:3000
> GET / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=utf-8
< Content-Length: 2
< Date: Wed, 11 Sep 2019 06:20:13 GMT
< Connection: keep-alive
<
* Connection #0 to host localhost left intact
```

@paramsinghvc You need to stop throwing every question that comes to mind here. Try the slack channel for general questions. However, if you think something is off or a bug, please provide a fully reproducible example (excluding 3rd party packages), like I did above.

**Comment by paramsinghvc** [comment]
I've attached the screenshot that it's not working. And the other confusing thing is that I'm using the remove method this way,

`const { request: req, response: res } = ctx;`
`res.remove('X-Powered-By');`


in contrary to your `ctx.remove`. Please explain whether there's a different between the two. You also need to provide sufficient documentation for the same considering people are using your framework in production and hence dependent on it completely.

**Comment by fl0w** [comment]
> I've attached the screenshot that it's not working. 

I can provide a screenshot as well. Now we're equal, right?

![Screenshot 2019-09-11 at 09 19 22](https://user-images.githubusercontent.com/71882/64676154-40817980-d475-11e9-8a63-c312a50b4bbd.png)

  1. In the context of development, a screenshot rarely describes the problem sufficiently. Yes I can see you still have Express (?) in your header but many questions arises. Why does it say Express? This is Koa. What else do you have in your code that might conflict with your intentions? What versions of node and Koa are you using?

  2. Without providing a small example (with anything unrelated to Koa omitted) I can only assume you're doing something wrong because I provided a simple, copy-paste example that does work. 

  1. If you got offended by my last response, it was not my intention. As I dedicate my own free time on open source software I have one rule for time management, **I only put in as much effort on my answer as the original poster does on the question.**

  3. This is not "my" library. I simply help maintain and bug fix because I myself depend on Koa. That's how open source works. This was written by much smarter developers than me.

  4. With open source software, you really shouldn't demand anything to be honest. If you feel the documentation is lacking, a PR is much appreciated. Koa is MIT licensed. Koa documentation is (by choice) only describing this library, not all variations and flavours of usage.

  5. Keep in mind that when you're posting an issue here, you're essentially asking volunteers about help. If you feel something's off, you need to describe the problem with sufficient context. Simply stating "it doesn't work" without a practical test case is actually quite offensive to all of the contributors of Koa.

```js
'use strict'

const Koa = require('koa')
const app = new Koa()

app.use(async ({ response }, next) => {
  response.set('X-Powered-By', 'Express')
  await next()
})

app.use(async ({ response }) => {
  response.remove('X-Powered-By')
  response.body = 'ok'
})

app.listen(3000)
```
```sh
$ curl -v localhost:3000
# ... abbreviated TCP connection output
> GET / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=utf-8
< Content-Length: 2
< Date: Wed, 11 Sep 2019 07:30:11 GMT
< Connection: keep-alive
<
* Connection #0 to host localhost left intact
ok
```

> Also, I couldn't find any issue raising guide in your readme for slack.

That's a fair point. It's not an "official" channel though so I'm not sure it ever will be. Though IRC, Stack Overflow are generally better venues to ask specific questions.

**Comment by paramsinghvc** [comment]
Don't know why there's so much fuss about creating a github issue in here! I'm already spending hours in debugging issues that I'm facing in your source code. Can't spend more arguing here.

**Comment by fl0w** [comment]
@paramsinghvc nobody minds having issues posted here, and I don't at all. But there's a minimum level of context that needs to be provided. Issues [like these](https://github.com/koajs/koa/issues/1379) helps nobody.

Again, please, feel free to open issues (that's what the question label is for) but provide some context.
