### ISSUE TITLE
Use of built-in URL object conflicts with supported Koa versions

### ISSUE THREAD

**Issue by tinovyatkin** [koajs/koa#1404]
Built-in [URL](https://nodejs.org/api/url.html#url_class_url), as used in [just one place in `response`](https://github.com/koajs/koa/blob/4f968298f97394e488297ec32c8e927a3a322076/lib/response.js#L292) was added in Node 6.13, while Koa `engines` is `"^4.8.4 || ^6.10.1 || ^7.10.1 || >= 8.1.4"`.
Should that be fixed?
Which way:
1. Introducing [whatwg-url](https://www.npmjs.com/package/whatwg-url)? 
2. Bumping `engines` a little?
3. Simulating `URL` object by adding hostname properties, etc?
4. Just document that?
5. Do nothing, nobody is using Node < 6.13 today.

**Comment by fl0w** [comment]
Those who are using node pre 6.x are probably transpiling using Babel. The engines was added to promote secure minimum versions, not to prohibit.

**Comment by tinovyatkin** [comment]
@fl0w sorry, may be I'm missing the point here. Babel will not polyfill URL in built-in `url` module. Do you vote for 2 (if Koa doesn't take `engines` seriously we can bump at least `^6.10.1` to `^6.13` in a patch version) or for 5?
`engines` can be an issue for people using `yarn`, as they are prohibitive there by default.

**Comment by fl0w** [comment]
I'm not saying it does polyfill. I'm saying that if we were to raise the minimum via package.json#engines we'd break the build. I proposed in #1114 to bump engines. Even though chances may be slim that somebody uses node 4.x and babel I have to assume a case exists. I respect semver too much.

If anything, this could be documented in a wiki or something. Even this issue is sufficient as documentation IMO :).

**Comment by miwnwski** [comment]
If I follow this correctly, this isn't an issue anymore as engines was bumped to >12 recently in master.
