### ISSUE TITLE
why use 404 of statusCode as the default response ?

### ISSUE THREAD

**Issue by beita1** [koajs/koa#1463]
- I am confused about the reason for setup 404 as default res.statusCode.
- If I don't set res.body or status code in my middleware,  it will use default statusCode and message.
 why not distinguish status code between unentered route and unset body?

**Comment by dead-horse** [comment]
I think 404 is the most appropriate status code for this scenario because you're not giving any response to the client.

How to distinguish unentered route and unset body is another issue that router middlewares should to resolve(if they want), for example they can add some customize header like `x-matched-route` to mark matched route.
