### ISSUE TITLE
why not remove `util.inspect.custom` condition?

### ISSUE THREAD

**Issue by anlexN** [koajs/koa#1501]
![image](https://user-images.githubusercontent.com/8686739/91125954-801c9200-e6d5-11ea-8faf-bde001681d4d.png)
all LTS node version support it.

**Comment by miwnwski** [comment]
You're correct, all *current* LTS versions, but Koa 2.x has node 4.x defined in engines. This will not be removed until Koa gets a semver major bump and we can drop old node support.

If you feel there's room for improvement please open a PR with suggested changes instead of these issues with underlined images. I'm going to close this.

**Comment by anlexN** [comment]
when to release Koa V3?

**Comment by miwnwski** [comment]
No timeline has been set.
