### ISSUE TITLE
SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by wlepinski** [koajs/koa#179]
Hi. I'm trying to follow the starter guide and I'm get the following error: 

``` javascript
var koa = require('koa');
var app = koa();

app.use(function *(){
  this.body = 'Hello World';
});

app.listen(3000);
```

``` bash
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

I'm using node 0.10.24 and executing the script using <code>node --harmony</code>

**Comment by dschinkel** [comment]
I'm having the same issue but mine is because I'm trying to create an instance of Koa from my Mocha test.  But when I run server.js otherwise such as from the command-line it works fine, it's just because my tests aren't probably being covered by babel or something however I believe I've configured babel correctly but for some reason Koa complains when I have the following in this example test:

server.js
------------
'use strict';

var supertestKoa = require('supertest-koa-agent');

var app = module.exports = require('koa')(),
    port = process.env.PORT || 3000;

supertestKoa(app);

app.listen(port, function(){
    console.log('Koa app is listening on port' + port);
});

myTest.js
-------------
'use strict';
var api = require('../../server.js');

var port = 3000;
var request = require('co-supertest').agent(api.listen(port, console.log('test app running' + port)));

describe('Feature: Obituary REST Endpoint', function () {
....rest of my code
};

package.json
-----------------
  "scripts": {
    "test": "mocha node_modules/.bin/mocha --harmony test --compilers js:babel/register test/**"
  },

Let me know if you need more like how I setup my gulp file for babel but when I run my test I get that error: 

search-api/node_modules/koa/lib/application.js:179
function *respond(next) {
         ^
SyntaxError: Unexpected token *
