### ISSUE TITLE
profile middleware  

### ISSUE THREAD

**Issue by tj** [koajs/koa#219]
just a reminder to myself: use compose hook to create a profiler layer that will report durations spend in each layer

**Comment by jonathanong** [comment]
let's just solve this once in for all in `koa-compose`. how about something like this:

```js
function compose(middleware, profiler){
  return function *(next){
    if (!next) next = noop();

    var i = middleware.length;

    while (i--) {
      var fn = middleware[i]
      var profile = profiler(middleware[i])
      next = function *(next) {
        profile.start()
        yield* next
        profile.end()
      }.call(this)
    }

    return yield *next;
  }
}
```

**Comment by jeromew** [comment]
(Replying to https://github.com/koajs/koa/issues/196#issuecomment-192083703)

What I would like to do with profiling is to have a way to profile whole koa application, even if I am using middlewares that have already been composed in other libraries. In production, you never know where a bottleneck is going to come from so a view on other modules would be a +.

the profiling system should also have close to no impact in production if profiling is not activated.

The way I see it (I have no implementation and am not sure if it makes sense) would be something like the `debug` module.

a module exporting middlewares could have a profiling name a-la debug.

Then at runtime via 2 environment variables, I could 

 * choose by name which middlewares I want to profile
 * define which profiler I want to use

I don't know if this makes sense to you.

Regarding the modification of koa-compose, I once proposed that we should be able to define our own composer (use `koa-compose` if you want no profiling, use `koa-compose-myprofiler' to have the behavior of myprofiler.

Adding the `profiler` variable directly to `koa-compose` adds some of this behavior but :

 * there is a systematic perf hit on the profiler mechanism even if I want no profiling
 * I don't see how I could profile third-party koa middlewares modules

Regarding the API, I proposed something in https://github.com/koajs/koa/issues/196#issuecomment-61021512 (maybe the code is not very clear). Basically, the idea to compose `middleware` was to

   * first map the `middleware`array to myprofiler(middleware[i])

````js
    var myprofiler = function *myprofiler(next){
       // things to do before
       yield *gn.call(this, next);
       // things to do after
    }
````

  * and then call `compose` on this new array

The difference I see is that you version is synchronous (there is no way to wait on `profile.start()` and `profile.end()`)

The API should probably give the user the choice of sync vs async. 
 * I could see a usage for a "step by step" profiler/debugger where I need to click "next" at every stage. 
 * I could also see scenarios where I could want to make sure something is logged before going to the next step even if it at a perf cost

But those scenarios are maybe far-fetched and I can live without them now.

Do we have some kind of list of applications that will be done with this profile mechanism / real world scenarios ? Do you know how the express, hapi or restify community handles profiling ? 

I have heard (but never tried to confirm) that restify has done a good job for profiling via its DTrace probes - http://restify.com/#dtrace . Maybe that could be something to explore too.

**Comment by PlasmaPower** [comment]
:+1: on that API. Wrapping the middleware seems like the best way to provide opportunities to profile it. In addition, there would be no need to check if there are profilers every time a request is received.

**Comment by jonathanong** [comment]
oh yeah, no problem making the profiler async.

i don't think we want to integrate any specific tracing because there are just so many of them. 

@jeromew would you like to make a PR to `koa-compose`? i think we're on the same page

**Comment by jonathanong** [comment]
though i'm not sure about the "choosing middleware by name" part. you could just use `debug` in the profiler as the profiler should receive the `fn` as an argument

**Comment by fl0w** [comment]
What about having a `app.profiler` available, which `Application.callback()` passes to when composing?

**koajs/compose/index.js** (next branch)
```js
function compose (middleware, profiler) {
  if (!Array.isArray(middleware)) throw new TypeError('Middleware stack must be an array!')
  if (profiler && typeof profiler !== 'function') throw new TypeError('Profiler needs be a function!')
  for (const fn of middleware) {
    if (typeof fn !== 'function') throw new TypeError('Middleware must be composed of functions!')
  }

  return function (context, next) {
    // last called middleware #
    let index = -1
    return dispatch(0)
    function dispatch (i) {
      if (i <= index) return Promise.reject(new Error('next() called multiple times'))
      index = i
      let fn
      if (profiler) fn = middleware[i] ? profiler(middleware[i]) : next
      else fn = middleware[i] || next
      if (!fn) return Promise.resolve()
      try {
        return Promise.resolve(fn(context, function next () {
          return dispatch(i + 1)
        }))
      } catch (err) {
        return Promise.reject(err)
      }
    }
  }
}

```

**koajs/koa/lib/application.js#callback**
```js
  callback() {
    const fn = compose(this.middleware, this.profiler);

    if (!this.listeners('error').length) this.on('error', this.onerror);

    return (req, res) => {
      res.statusCode = 404;
      const ctx = this.createContext(req, res);
      onFinished(res, ctx.onerror);
      fn(ctx).then(() => respond(ctx)).catch(ctx.onerror);
    };
  }
```

**example.js**
```js
app.profiler = function(fn) {
  return (ctx, next) => {
    const start = process.hrtime()[1]
    console.log(fn.name + ' > ' + start)
    return Promise.resolve(fn(ctx, next)).then(() => {
      const end = process.hrtime()[1] - start
      console.log(fn.name + ' < ' + end + ' (' + end/1000000 + ')')
    })    
  }
}

app.use((ctx, next) => {
  console.log('start a')
  return next().then(() => {
    console.log('end of a')
  })
})

app.use((ctx, next) => {
  console.log('start b')
  return next().then(() => {
    console.log('end of b')
  })
})

app.use((ctx, next) => {
  console.log('start c')
  return next().then(() => {
    console.log('end of c')
  })
})

app.use((ctx, next) => {
  ctx.body = 'hello worl2d'
})
```

**Comment by PlasmaPower** [comment]
@fl0w I like the idea, I think that was the API discussed above. However, I'd prefer if it was called something more general than profiler, as the API isn't profiler specific. We should also consider if it should be an array, or just a single function.

**Comment by jeromew** [comment]
@fl0w I think this is in line with what we are discussing (for the promise based version) but I don't know if we want a compulsory "everything-is-profiled" approach.

@jonathanong I haven't tried to push a PR because I am working on other subjects right now and even though this feature has been long standing I do not want to rush it in koa. profiling is a key feature for a mature framework and I think that options should be compared on real life scenarios - at least performance wise since wrapping every middleware is not a cheap operation.

As I see it profiling can already be done by something who accepts to wrap all its middlewares

    app.use(wrap(mw1))
    app.use(wrap(mw2))
    app.use(wrap(mw3))

For logging purpose, I try to give names the middlewares

sometimes, I pre-compose middlewares like `app.use(compose(mws))`. This could be replaced by

    app.use(composewrapper(mws, logger, "myname"))

which would compose a logger version of all the mws and give the name "myname" to the resulting middleware.

This gets burdensome at some point + there are probably subtleties when dealing with middlewares coming from other npm modules, or middlewares created/composed at runtime in specific branches inside a middleware.

What I would want is :
 - to be able to profile all the middlewares in an application or specific parts of an application ; maybe have a guideline for external modules so that they can become profileable.
 - with a clean API that would avoid the need to wrap every single middleware.
 - the profiler should be able to output an clear view of the middleware chain that the request went through

Is there already a big user-facing open source projet that use koa (like ghost or nodebb) that we could use as a testbed an say "let's add profiling to this project" ?

**Comment by fl0w** [comment]
@PlasmaPower I agree, I used the term profiler for illustration-purposes. I think I agree the act of "wrapping" or "wrap" is more appropriate as you and @jeromew highlight.

@jeromew I think your cases are entirely possible with the proposition, but instead of hard-coding a "one size fits all"-solution, just delegate it to user space.

You could just have a wrap-mw that simulates what debug does, which listens to desired env. E.g. `process.env.PROFILE=my:personal*`.

One could also just not use the Koa provided `app.profiler`, instead opt to `compose` manually

```js
app.wrap = false // default
app.use(compose(['my', 'middleware', 'stack', 'im', 'interested', 'in'], aProfilerIMade)
```

If I had some specific use cases or desires, I wouldn't expect Koa to solve app-specific probe:ing anyway.

**Comment by Student007** [comment]
Are there special quality requirements for Koa 2.0 middleware ? I mean things like tests for new features ? Maybe it could be a list of tasks ? If there is no list it would be nice if someone of the core developers give me a hint how to increase software quality from your point of view (to middleware developers). I would assume there is a feature list which should be checked whether there are use cases affecting a middleware which should cause writing a test within the middleware repository. I think also tips for processing such tasks would be helpful - for instance one could copy some tests from the core and change them by the middleware behavior.
My goal is to learn something by making the koa-sub-domain router 2.0 ... :smile:

**Comment by jonathanong** [comment]
@PlasmaPower @fl0w @jeromew sorry for not being more active. been a little busy. there's a bunch of PRs open that I haven't really looked into. here are my questions, and as long as we have a consensus on these, we should write them down somewhere in the docs and have tests for them. then, it is about implementation details, of which i prefer the simplest solution.

- should mounted apps/routers wrap their middleware too?
  - for example, `app.use(router)` or `app.use(anotherApp)`
  - how do you handle apps with wrappers mounted onto another app with wrappers? parent app wrappers wrap the child app wrappers?
- should every "decorator" be wrapped as well?
  - for example, `koa-route` wraps another middleware as an if-statement. should the `koa-route` decorator be wrapped as well the actual middleware being decorated? this allows you to debug that the routing logic was executed, but not the main logic
  - this could be chosen on a per-middleware basis (implementatiors will decide). we would then need some exposed function like `app.wrap()` or `this.wrap()` to make this easy for every middleware. or have middleware require a 3rd party module that calls the wrapped function

implementation questions (less important):

- should we store the wrappers on `app` or on `context`? @PlasmaPower has convinced me that only having it on `app` would make routers more difficult since you would need to pass `app` to every middleware. maybe `app.wrappers` and have `ctx.wrappers` delegate to it?
- should we wrap the last middleware (response)?

@koajs anyone else have questions? if someone wants to start a gist about the specs, that would be great

**Comment by PlasmaPower** [comment]
> should mounted apps/routers wrap their middleware too?

I think everybody is assuming that yes, they should. This would be the same way as compose handles it.

 > how do you handle apps with wrappers mounted onto another app with wrappers? parent app wrappers wrap the child app wrappers?

I'd assume the child wrappers would get applied first, then the parent wrappers. However, I don't think you can currently mount a Koa app with use(), correct?

> should every "decorator" be wrapped as well?

Yes, I think this makes the most sense and would allow for profilers to create a nice tree.

> we would then need some exposed function like app.wrap() or this.wrap() to make this easy for every middleware

My newest PR implements this as `app.prepareMiddleware` (it also does some other stuff, hence the name). My older PR has this as it's own library.

> should we store the wrappers on app or on context?

Most implementations store them in the context, but with mw._wrappers or mw.onUsed (the two most recent PRs) they can be stored in the app.

> should we wrap the last middleware (response)?

I don't think any PRs currently do that, but I think we could (at least with my most recent PR, haven't checked the others). If we decide to do that, I can easily change my PR.

**Comment by jonathanong** [comment]
it seems like i'm the only collaborator really involved in this, and it's not something i want to be decide on alone.

@PlasmaPower thanks for your hardwork. do you want to try making this a separate module first that augments a koa app? we can add it to the org

**Comment by fl0w** [comment]
Out of curiosity, would a wrapper be a middleware or a function returning a wrapped middleware? I'm so confused at this point I'm stalled.

**Comment by PlasmaPower** [comment]
@fl0w A function returning a wrapped middleware. For example, here's an extremely simple profiler:

```js
let wrapper = function (mw) {

};
```

**Comment by jonathanong** [comment]
they decorate middleware. all the wrappers will decorate all the middleware.

**Comment by fl0w** [comment]
@PlasmaPower @jonathanong Right, so that's equivalent to the very very first example I did.
So what's the negative about assigning the wrappers to mw._wrappers and let compose reduce by those if provided?

**Comment by PlasmaPower** [comment]
@fl0w Because compose doesn't reduce - with compose wrappers would just be middleware that ran before every middleware.

**Comment by RobertHerhold** [comment]
This would be a really handy feature to have. Are there any plans to continue this?

**Comment by fl0w** [comment]
@RobertHerhold There's been so much bikesheeding at this point I'm not sure. Even then, I'm personally getting a feeling that composing middleware at large through Koa is sort of useless since async-await. It's an anti-pattern as far as I'm concerned. I don't see any benefit *(except for current statue quo mw ecosystem)* over just having a single mw and calling whatever feature with await, e.g.
```js
const myAppMiddleware = async (ctx, next) => {
  await middlewareOne(ctx)
  await middlewareTwo(ctx)
  if (logic) {
    await myRouter(ctx)
  }
  ...
}
```

At which point it's easy to just profile in between, or wrap, each call with whatever profiler poison you choose. They're all just mutating and using ctx anyway. I do see the benefit, however. Such as parallelism (if some mw do IO), less clutter in stack (no extra wrapping with promises), and just generally not needing compose in koa :).

**Comment by joemckie** [comment]
For anyone interested, I just released a package that does exactly this. It works via dependency injection, so you can pass in your own logging function, if you happen to use something like winston.

https://www.npmjs.com/package/koa-profiler-middleware

**Comment by fl0w** [comment]
@joemckie that doesn't profile a middleware, it simply counts how long the full request takes.

Equivalent to e.g.
```js
app.use(async (ctx, next) => {
  const start = process.hrtime.bigint()
  await next()
  const end = process.hrtime.bigint()
  console.log(`Request took ${end - start} nanoseconds`)
})
```

... or https://github.com/koajs/response-time

**Comment by joemckie** [comment]
@fl0w yep you're right, completely misread this thread 🤦‍♂

**Comment by jonathanong** [comment]
closing this, better to just profile each async function
