### ISSUE TITLE
this.accepts with */* not practical

### ISSUE THREAD

**Issue by aj0strow** [koajs/koa#240]
Just getting started with koa, and already love it!

One thing tho - I want to serve a single page app with pushState urls. The problem is that chrome includes `*/*` at the end of the Accept header with every request.

``` javascript
app.use(function *(next) {
  if (this.accepts('html')) {
    // always true
  }
});
```

I know its _technically correct_ that the browser accepts html for an image request, but not sure what the method is for if I use the following anyway:

``` javascript
~this.get('accept').indexOf('html')
```

Let me know what you guys think. Thanks!

**Comment by yanickrochon** [comment]
Even if this is "how things are", and how browser can accept anything, having a strict option would be quite handy. For example, in the case where I have an `Accept` header equal to `application/json, text/javascript, */*; q=0.01`, I'd not expect `this.accept('html')` to return `html`. Even though the content type is handled by the browser, the point of interest in at the server side.

I'm having this issue since some images are behind the auth middleware (restricted), as well as some JavaScript files that can only be access if the user is authenticated.

The problem I'm having is : should I redirect or should I return 401?

As the example I gave above, if a public script performs a query to a restricted resource, I don't want a 302 redirect, but a 401 to be issued. So, and since `*/*` exists in that header field, I need to test most common content types instead of just checking is `html` is explicitly specified (i.e. not as a wildcard).

What about a `this.acceptOnly('html');` that would not match wildcards?

----
**Note**: locking threads ( #440 ) before one can reply is rude, @dougwilson . I just wanted to mention this. /end-of-off-topic.

**Comment by dougwilson** [comment]
@yanickrochon , it is rude to hijack threads.

**Comment by dougwilson** [comment]
Also, @yanickrochon , no one will see your reply here, because the community does not hunt through threads closed for over a year. If you want the community to see and discuss your proposal, you need to open a new issue, so people will actually see it.

**Comment by yanickrochon** [comment]
If this is re-opened, then people will see it. I just don't see the purpose of creating a new issue when this is exactly in context, unless one really wishes to have the issue in 1st place... After all, I found this with a simple search (i.e. removing `in:open`).

**Comment by dougwilson** [comment]
Ok, @yanickrochon . Typically I leave it up to the user that closed the issue to re-open the issue, so we shall wait :)
