### ISSUE TITLE
question : where can I find the best help on koa.js

### ISSUE THREAD

**Issue by roelof1967** [koajs/koa#392]
Hello, 

I have a problem with koa.js with content-type. 
I have asked several days ago on the google group and on the google community but nobody give me a answer. Also I looked on IRC but nobody seems to be there at European time at day time 

So my question is where can I find the best place to ask questions about koa.js

**Comment by hallas** [comment]
I think here or using gitter

**Comment by hallas** [comment]
also there may be a help repo somewhere?

**Comment by roelof1967** [comment]
I have asked in gitter and the problem Im facing is stated here : https://groups.google.com/forum/#!topic/koajs/7sAxdrH3fow

**Comment by mattma** [comment]
After reading @roelof1967 's question on googlegroup, I think that I could answer your question. 

This is my solution to the problem which is very similar to the original solution without `if-else` shorthand,

```js
app.use(function* (next) {
  // Checking the header's type of the request
  var type = this.request.is('application/json');
  
  // if the request type is `json`, send `{message: hi}`
  // if `text/plain` or `text/html` or anything else, return plain text `ok`
  if(type) {
    this.body = {
      message: 'hi!'
    };
  } else {
    this.body = 'ok';
  }
});
```

You asked the questions `but I miss there that the headers are sent back.
What is the best way to do that ?`

If I understand your question correctly, here is my answer, if not, please, explain in details,

Koa would automatically assign the content type based on the content type of the `this.body` content. If it is a string, it would use `text/plain`, if it is `html`, it would use `text/html`, if it is `json`, it would use `application/json`. So you won't need to do anything in this case. Koa should take care of it for you. 

`json` is the first class citizen which koa supports so that makes Koa be the best framework to handle API end point, and several other great use cases. 

If you look at the source code in `lib/response.js`, setter function of `body(val)`.=, Internally, `this.body` uses `this.type` to assign the content type. And `this.type` would call [mime-types](https://github.com/jshttp/mime-types) `contentType` function to do all the hard work(lookup content type), then assign back to the Koa
s `context` property `type`. 

Koa shares the same middleware along with Express (awesome), so that community/project maintainers would maintain the middlewares in both frameworks.

**Comment by roelof1967** [comment]
Thanks for this explanation. I had the impression that I have to set the content -type after reading the line. So it appeared that im mistaken.
