### ISSUE TITLE
es7 async function feedback

### ISSUE THREAD

**Issue by jonathanong** [koajs/koa#415]
es7 async functions are now supported when you enabled `app.experimental = true`. it uses https://github.com/thenables/composition. however, the last time i benchmarked it, it was significantly slower.

please provide feedback and maybe do some benchmarks and performance improvements so we can one day support es7 async functions by default without sacrificing anything :)

**Comment by juliangruber** [comment]
:+1:

**Comment by mpal9000** [comment]
:beers:

**Comment by calebboyd** [comment]
This looks awesome. I did some dabbling with a different composing mechanism with only promises and async await. Thought maybe I should post it here for feedback

```javascript
function compose (middleware) {
  let noop = () => Promise.resolve()
  let responses
  let next
  middleware = middleware.map((mw, i) => {
    return function (){
      next = () => (middleware[i+1] || noop).call(this)
      return responses[i] = mw.call(this, next)
    }
  })
  return async function composed(){
    responses = new Array(middleware.length)
    await middleware[0].apply(this, arguments)
    return Promise.all(responses);
  }
}
```
[gist](https://gist.github.com/calebboyd/536dd04ce840f9102aeb)

Using babel with `bluebirdCoroutines` enabled this method achieved better marks than the default implementation (koa-compose). Its also a little (lot?) different in that you must invoke `next` but I think that gives more control (concurrent vs sequential etc.)

Thoughts/Criticisms?

**Comment by tj** [comment]
I wouldn't want to change the `next`-ing API-wise, it's useful to allow middleware to break the down stream to short-circuit.

Perf-wise I'd have to see some numbers! That's not really a huge concern though, less deps/complexity is a nicer win. We're already achieving numbers that would sustain most applications with a single node, and no production app will have a single node so that's less of a concern.

**Comment by calebboyd** [comment]
@tj Hah, good point... 
On a really slow VM..
Standard Azure D2 (2 cores 7Gb ram) with Ubuntu 14.04 - node 0.12.0

| #MW | koa    | koa async await bluebirdCoroutines | koa async await asyncToGenerator |
|-----|--------|------------------------------------|----------------------------------|
| 1   | 3392.4 | 3422.7                             | 2180.7                           |
| 5   | 3109.8 | 3303.7                             | 1751.6                           |
| 10  | 3128   | 3223                               | 1460.7                           |
| 20  | 2889   | 2988                               | 1039                             |
| 50  | 2630   | 2635.6                             | 593.6                            |

This could be quite different in versions of io.js (for native promises)
Since bluebird certainly isn't lightweight this doesn't do much for shedding dependencies...

I'm thinking I can still short-circuit with this mechanism too..
are you suggesting upstream be invoked all together?

I should mention that this pattern is not my own. Its copied from the way OWIN and Katana (.NET) handle their async await middleware.

**Comment by zensh** [comment]
I don't like `next-ing API`, it will lead to another **callback hell**.
However, `next-ing API` is core mechanism in koa that can't be disable, so I create a [toa](https://github.com/toajs/toa) that similar to koa. 

@tj sorry~

**Comment by tj** [comment]
Next probably won't be going anywhere, having proper middleware is a lot more flexible than the Express style, but use whatever works for you obviously!

**Comment by Globegitter** [comment]
@jonathanong Just wanting to get started doing some performance testing and having issues getting the new syntax to work:
```js
var koa = require('koa');
var app = koa();

app.experimental = true

// logger
app.use(async function (next){
  var start = new Date;
  await next;
  var ms = new Date - start;
  console.log('%s %s - %s ms', this.method, this.url, ms);
});

// response
app.use(async function (){
  this.body = 'Hello World';
});

app.listen(3000);
```

Is this supposed to work? Or did I misunderstand something with the syntax?

**Comment by hallas** [comment]
What error are you getting?

**Comment by Globegitter** [comment]
Running on io.js 1.2:
```js
/Users/markus/Projects/Artificial/koa-test/index.js:19
app.use(async function (next){
              ^^^^^^^^
SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:429:25)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Function.Module.runMain (module.js:487:10)
    at startup (node.js:111:16)
    at node.js:799:3
```

**Comment by jonathanong** [comment]
sorry, instructions are probably unclear. you need to use babel to enable `async` functions. here's the test file as an example:

https://github.com/koajs/koa/blob/master/test/experimental/index.js

**Comment by Globegitter** [comment]
Ahhhh, I was almost thinking that. But also a bit surprised because `babel` was made a devDependency with the latest version. So we should install that manually for the time being in our project?

**Comment by dougwilson** [comment]
> So we should install that manually for the time being in our project?

Yes

**Comment by Globegitter** [comment]
Ok thanks all working now - let the happy testing begin :)

**Comment by ide** [comment]
@calebboyd would you happen to have your benchmark code laying around? I'm curious as to why asyncToGenerator is so much slower than plain koa since the two should be doing roughly the same thing. As I understand it, both wrap native generator functions to create functions that return promises, using the built-in Promise class.

**Comment by jonathanong** [comment]
https://github.com/thenables/composition/issues/1

**Comment by calebboyd** [comment]
@ide the benchmark I had above used promise based middleware instead of the included genereator based. The comparable performance I believe is due to koa using plain generators (not wrapped, good performance). Where asyncToGenerator wraps generators in promises, which is then wrapped again by the composition function. But when using promise based mw and bluebird, intermediate promise allocations are avoided (bluebird optimization).

**Comment by ide** [comment]
Thanks, guys.

**Comment by mgenev** [comment]
@calebboyd any chance that example can go public on github?

**Comment by calebboyd** [comment]
@mgenev What are you looking for exactly? The basic gist is posted above. The problem is that it breaks koa's generator based api and consequently anything implemented with it :/ .  mho as expressed in  #420 Is that promise based middleware should be used if koa uses async await. As it seems we might eventually get `async await` optimization -- but that probably won't apply to 'thenables'

I can probably add a fork with the changes...

**Comment by mgenev** [comment]
@calebboyd  I got a lot of it working with bluebird coroutines and the composition from the OP, but when i start routing I'm getting confusing errors like
 `Unhandled rejection Error: Can't set headers after they are sent.`  or 'undefined is not a function' with 'asyncToGenerator' , I think it's because koa-router is dependent on koa-compose, not the above mentioned composition module.

**Comment by thelinuxlich** [comment]
Better use something like Earl Grey: http://breuleux.github.io/earl-grey/ while the native option is unavailable

**Comment by chovy** [comment]
You can use babel on the server side to get async/await. (i have not done this though, so I can't be of much help).

**Comment by cesarandreu** [comment]
Was playing around with async/await in koa, I keep getting `A promise was converted into a generator, which is an anti-pattern. Please avoid using `yield* next`!`, and I'm not sure why. I'm gonna look into it later.

None of the routers work well with async functions :(. I'm using koa-router, and as a stopgap I'm doing:

```js
const routes = new Router().get('/foo', compose([a, b, c]))
```

**Comment by mgenev** [comment]
@cesarandreu That was my experience as well, so I opened an issue which is referenced above, but so far no response. It's kind of a silly situation because I've ben able to use async/await in an express app, but not koa which is built for the future JS

**Comment by dmtrs** [comment]
@cesarandreu Could you share more on what you are actually doing in `[ a, b, c ]` functions?

**Comment by cesarandreu** [comment]
Certainly, this is one of my files right now:

*posts.controller.js*

```js
const middleware = require('../utils/middleware')
const compose = require('composition')
const Router = require('koa-router')

// @TODO: Replace koa-router with an async function friendly router
export default function PostsController () {
  // Middleware
  const loadPost = middleware.load('Post', {
    key: 'name'
  })

  // Routes
  const routes = new Router({
    prefix: '/api'
  })
  .get(
    '/posts',
    compose([
      PostsController.index
    ])
  )
  .get(
    '/posts/:post',
    compose([
      loadPost,
      PostsController.show
    ])
  )

  return routes.middleware()
}

/**
 * GET /api/posts
 */
PostsController.index = async function index () {
  const {Post} = this.models
  this.body = await Post.findAll({
    order: [
      ['createdAt', 'DESC']
    ]
  })
}

/**
 * GET /api/posts/:post
 */
PostsController.show = async function show () {
  this.body = this.state.post
}
```

When I create my API app I add my models to the context pretty high up. For the `/posts/:post` route I create an instance of the load middleware, which will just read `:post` in the url and load it from the database, searching by name. If it find it it'll get set on `ctx.state`, otherwise it'll return a 404. `PostsController#show` just responds with the model.

**Comment by jonathanong** [comment]
yeah a lot is going to have to change to get routers to support it.

**Comment by jonathanong** [comment]
so from this conversation, the issue i see is that it doesn't work with `koa-compose`, correct?

**Comment by mgenev** [comment]
yep that's what I found out when I tried, and all the routers are based on koa-compose

**Comment by jonathanong** [comment]
well... we should get this working before 2016. do you guys think we should try converting stuff from `koa-compose` to `composition`? i guess the question is - should the end-goal be to only use `async/await` and never generators?

**Comment by ide** [comment]
> should the end-goal be to only use async/await and never generators?

This sounds right. Generators for control flow were a stepping stone to async functions.

**Comment by mgenev** [comment]
I personally vote a big yes, I've been using the 2 this year and I'd rather always use async/await for this. It's also the sentiment expressed by axel rauschmayer, hussain jafar and other leaders of JS

**Comment by cesarandreu** [comment]
@jonathanong yup, the lack of router support is the biggest blocker. I haven't tried any performance benchmarks, though.

Is there a more compelling reason to get rid of generator support, other than it's a bit hacky (e.g. performance gains)? Otherwise, -1 on removing generator support from `composition`. There's a lot of existing middleware and applications that are already using generators, and async/await is only usable with babel and a flag. I'd vote for keeping generator support in but suggesting people move to async/await.

**Comment by jonathanong** [comment]
imo it's performance and supporting two APIs. way easier if we only supported async/await, but i only intend to do that when async/await works in node without `--harmony`, so there'll be a period where both is supported.

**Comment by jonathanong** [comment]
anyone against making `composition` default? if we make it default, it would be easier to update routers wtih `composition` and `async`/`await` support

**Comment by thelinuxlich** [comment]
Does it hurt performance?

**Comment by jonathanong** [comment]
probably

**Comment by hallas** [comment]
@jonathanong If you think it's best then I think go ahead. Just let us know how we can switch back to the current setup if needed

**Comment by jonathanong** [comment]
hmmm maybe there's a better way... like passing the `.experimental` flag to `composition/compose` somehow

**Comment by hallas** [comment]
Your call. As long as it's possible to revert individually. I think however in terms of ES updates it's super important that co, koa and that family of projects stay at the bleeding edge until the dust settles.

Sorry I haven't had the time to research any better options

**Comment by thelinuxlich** [comment]
Then I'm against it :(

**Comment by cesarandreu** [comment]
It hurts performance pretty badly. Using ab I tried out one of my apps, with a small number of middleware, I got a 30% performance improvement by replacing async functions with generators. (In both cases they were being transpiled by babel.)

**Comment by ide** [comment]
There was an update to regenerator 0.8.32 seven hours ago that includes some perf improvements (40x in specific circumstances I believe). The latest version of Babel ships with it. Might want to give it a try.

**Comment by hallas** [comment]
@cesarandreu Can you run it with the latest Babel that @ide described?

**Comment by jonathanong** [comment]
was looking into adding an `experimental` option to `koa-compose`, but I couldn't get it to work - https://github.com/koajs/compose/pull/26 if anyone wants to look at it. 

easier solution would be to push routers to use `composition`, I suppose. do you guys want to push for it or should i? which routers is everyone using?

**Comment by jonathanong** [comment]
btw it should probably be another `experimental` option in these routers. ideally, it would grab it from `app.experimental` if the router is passed the `app` instance.

**Comment by tsing** [comment]
@jonathanong We are using `koajs/route`, will happy to test it if you add the `composition` to the router.

**Comment by jonathanong** [comment]
@tsing that module uses niether `koa-compose` nor `composition` though

**Comment by inca** [comment]
Am I right to assume that current benchmarks rely on transpiled code that simply converts `async function` stuff to generators using rewriting and `spawn` (like it [was proposed here](https://github.com/jhusain/asyncgenerator))?

If so, I don't quite understand, why these performance issues arise in a first place. I assume that native async/await will be pretty optimized and won't cause any noticeable performance impact.

**Comment by inca** [comment]
Sorry, wrong link. I actually meant [regenerator](https://github.com/facebook/regenerator).

**Comment by elgerlambert** [comment]
I was experimenting with koa + async/await and ran into the same issues with routing as described above (and backed off as a result). Happy to see this discussion taking place!

If a router switches to composition will it lose it's support for generators? How much buy-in is required to make that transition? Fixing koajs/compose#26 sounds like a much smoother transition path or is that not really an issue (just bump a major version and make the switch?)?

**Comment by ide** [comment]
One perf-related point I wanted to bring up is that Node 4.0 is coming soon and ships with a stable version of generators. There's a chance that async functions compiled to native generators (see Babel's asyncToGenerator option) run faster than generators compiled to callbacks (the status quo w/regenerator). "Faster than before" would be a good first step on the way to "as fast as possible".

**Comment by gyson** [comment]
Come out with a Promise-based middleware solution which could work with Promise,
generator function and es7 async function.

List a few advantages:
* Simple to implement. Just function composition without dependency. No need to require co.
* Performance improved by eliminating intermediate generator or wrapper.
* Compatible with all exists Koa middleware (`yield next`, `yield* next` or `await next`) with a wrapper.

[Implementation](https://github.com/gyson/shan) and [benchmarks](https://github.com/gyson/shan/tree/master/benchmarks) are available to check.

Code snippet as following:

```js
// use promise
app.use(next => function (context) {
    // before
    return next(context).then(function () {
        // after
    })
})

// use async function
app.use(next => async function (context) {
    // before
    await next(context)
    // after
})

// use generator function with co
app.use(next => co.wrap(function* (context) {
    // before
    yield next(context)
    // after
}))

// use generator function with bluebird
app.use(next => Bluebird.coroutine(function* (context) {
    // before
    yield next(context)
    // after
}))

// use koa middleware
app.useKoa(function* (next) {
    // context as `this`
    // before
    yield next
    // after
})

app.useKoa(function* (next) {
    // context as `this`
    // before
    yield* next
    // after
})

app.useKoa(async function (next) {
    // context as `this`
    // before
    await next
    // after
})
```

**Comment by jonathanong** [comment]
yes, the only issue is performance!

**Comment by jonathanong** [comment]
@gyson that code is unnecessary. the experimental version supports any function that returns a promise

```js
app.use(async function (next) {
  await something()
  await next
})

app.use(next => {
  return doSomething()
  .then(() => somethingElse())
  .then(() = next)
})
```

**Comment by drewhamlett** [comment]
Include a router in koa to get around routing issue.
![imgres-1](https://cloud.githubusercontent.com/assets/1056587/9480278/484d8da0-4b50-11e5-8616-daa7b0e4b8b9.png)

I would love to see async await in with support in routers.

**Comment by gyson** [comment]
@jonathpnong It's about simplicity and performance.

The key difference is to use `await next(context)` instead of `await next`.

`next` in `await next` need to contain info about context and next middleware. Therefore, we have to create wrapper for every middleware.

`next` in `await next(context)` only need to contain info about next middleware. Therefore, we can reuse middleware function and no intermediate wrapper at all.

Alternative API (close to koa's middleware) would like following:
```js
compose([
    function (next) {
        console.log(1)
        return next(this)
    },
    function* (next) {
        console.log(2)
        yield next(this)
        console.log(5)
    },
    async function (next) {
        console.log(3)
        await next(this)
        console.log(4)
    }
])
```
the implementation of above `compose` function is [here](https://github.com/gyson/koa-benchmarks/blob/2da094ef398d2ede1e3c7dcd1a43ec1e707ed348/koa-next-as-function/lib/compose.js).

The [benchmark](https://github.com/gyson/koa-benchmarks/blob/2da094ef398d2ede1e3c7dcd1a43ec1e707ed348/README.md) shows that eliminating immediate wrapper can improve performance as following:

| #middleware | 1 | 25 | 50 | 75 | 100 |
|:---|---:|---:|---:|---:|----:|
| [`await next`](https://github.com/gyson/koa-benchmarks/blob/2da094ef398d2ede1e3c7dcd1a43ec1e707ed348/koa-next-as-wrapper/async-await.js) | 9250.79 | 6363.05 | 4824.54 | 3567.84 | 2798.89 |
| [`await next(context)`](https://github.com/gyson/koa-benchmarks/blob/2da094ef398d2ede1e3c7dcd1a43ec1e707ed348/koa-next-as-function/async-await.js) | 9342.62 | 7526.55 | 6479.24 | 5607.01 | 4919.38 |

`yield next(context)` or `await next(context)` does not change the core idea about Koa middleware system and it works with `yield next` with a converter.

I have seen this middleware pattern in a few web frameworks (e.g. PHP Laravel, Golang Negroni) and I think this would also work very well for Koa.

**Comment by jonathanong** [comment]
i don't disagree. biggest problem is backwards compatibility.

**Comment by thelinuxlich** [comment]
It's not like Koa has a LOT of plugins and the migration wouldn't be trivial anyways :P

**Comment by gyson** [comment]
All exists koa middleware can be converted to it.

A naive implementation as following:
```js
function* lazy(next) {
    return yield next(this)
}
function convertKoaMiddleware(genFun) {
    return function (next) {
        return co.call(this, genFun.call(this, lazy.call(this, next)))
    }
}
```

**Comment by ide** [comment]
Could koa 1.1 (easily) offer an option to go wrapper-free along with a helper npm package that can add back the wrapping on a per-middleware basis? From what I'm reading, wrapper-free koa could offer better performance and with async functions we get a better API.

As a user I'd be happy if I could turn off the wrapper and manually add it back by decorating existing middleware with something like `convertKoaMiddleware`. Then as middleware and my own functions get modernized I could remove the ` `convertKoaMiddleware` calls and eventually get to a wrapper-free world. Finally after the most popular middleware are converted, koa bumps to 2.0 and removes wrapper support altogether.

Anyway I'm mostly trying to push along the discussion here to reach a decision. It seems clear to me at least that everyone wants to do something but isn't sure what yet.

**Comment by tj** [comment]
Just my opinion but I'd favour nice API and backwards compat over slight perf benefit, most deployments do not really need 10M requests a minute from a single node, any real production system will have at _least_ three nodes anyway

**Comment by gyson** [comment]
It takes me some time to finish following complete proposal.

@jonathanong It's backwards compatible.

@thelinuxlich Migration should be easy.

@ide yeah. We could add this to something like koa@1.1, since it's backwards compatible.

@tj The performance benefit could be significant. It depends on the use case.

## Goals

* Support async function and [async arrow function](https://tc39.github.io/ecmascript-asyncawait/#prod-AsyncArrowFunction)
* Decouple co and koa (koa does not need to depend on co any more)
* Significant performance improvement for common case

## Proposal: Promise-based Middleware

Promise-based middleware is a function with two arguments, `ctx` and `next`, and return `any` or `Promise<any>`. If `any` is returned, it will be wrapped to Promise using `Promise.resolve(value)`. If there is any exception, the error will be wrapped to Promise using `Promise.reject(error)`. The Promise result will be returned to previous middleware caller.

Note that it makes context as first argument instead of `this` for supporting arrow function and async arrow function.

```js
// ctx: KoaContext
// next: (KoaContext) => Promise<any>

app.use((ctx, next) => {
    console.log(1)
    return next(ctx).then(() => {
        console.log(8)
    })
})

// use async arrow function, may need help from babel
app.use(async (ctx, next) => {
    console.log(2)
    await next(ctx)
    console.log(7)
})

// use co
app.use(co.wrap(function* (ctx, next) {
    console.log(3)
    yield next(ctx)
    console.log(6)
}))

// use bluebird
app.use(Bluebird.coroutine(function* (ctx, next) {
    console.log(4)
    yield next(ctx)
    console.log(5)
}))
```

## Performance

Generator / async function is not free. It comes with a cost to use it.

There are many non-async middleware that did not really use `yield` except do `yield next`. Therefore you are paying for the feature that you don't need. This cost is not cheap since it will repeat for every middleware.

Some sample code as following:

```js
// you did not really use `yield` except `yield next`.
// cost for each middleware:
//   1. create a generator as `next`
//   2. do `yield next`
//   3. convert generator to Promise by co.
//   4. call `.then` to get value from Promise (defer to next tick and create another Promise)
let before = function* (next) {
    if (some_condition) {
        return yield next
    }
    // some sync operation
    return yield next
}

// the equivalent one in promise-based middleware would be

// cost for each middleware: none
let after = (ctx, next) => {
    if (some_condition) {
        return next(ctx)
    }
    // ...
    return next(ctx)
}
```

In generator-based middleware, you always need to create co instance and call `.then` for every middleware, which will result a `.then(...).then(..).then(...)` chain.

In promise-based middleware, you can just call `next(ctx)` and pass the promise result from next middleware to previous middleware by `return`. No co instance or `.then` cost.

In this case, the performance benefit could be significant.

The [benchmark](https://github.com/gyson/koa-benchmarks/tree/0ff11c41533707fcbeb8476c0a28b38cdb6a1380) result as following:

| API | 1 | 25 | 50 | 75 | 100 |
|:---------|--:|---:|---:|---:|----:|
| [`return yield next`](https://github.com/gyson/koa-benchmarks/blob/0ff11c41533707fcbeb8476c0a28b38cdb6a1380/koa-next-as-wrapper/generator-yield.js) | 8847.43 | 5383.50 | 3525.02 | 2819.64 | 2097.64 |
| [`return next(context)`](https://github.com/gyson/koa-benchmarks/blob/0ff11c41533707fcbeb8476c0a28b38cdb6a1380/koa-next-as-function/function-return.js) | 10206.70 | 10185.36 | 10109.08 | 9923.81 | 9759.48 |

When you need generator / async function, just use it. When you don't need this feature, you should not pay for it.

## Backwards Compatible

Let `compose` check type of the function. If it's GeneratorFunction, then we convert it to promise-based middleware implicitly.

```js
function compose(middleware) {
    middleware = middleware.map(fn => {
        if (fn.constructor.name === 'GeneratorFunction') {
            return convertKoaMiddleware(fn)
        } else {
            return fn
        }
    })
    // ...
}
```

Then it works like this:

```js
// I can detect that it's GeneratorFunction
// I will convert it implicitly
app.use(function* (next) {
    yield next
})

app.use((ctx, next) => {
    return next(ctx)
})

// I can detect that it's GeneratorFunction
// I will convert it implicitly
app.use(function* (next) {
    yield* next
})

app.use(async (ctx, next) => {
    await next(ctx)
})
```

## Migration

Just change following:

 * `this` to `ctx`
 * `yield next` to `yield next(ctx)`
 * `return yield next` to `return next(ctx)`.

```js
let before = function* (next) {
    // ...
    yield next
    // ...
}

let after = co.wrap(function* (ctx, next) {
    // ...
    yield next(ctx)
    // ...
})
```

## Give it a try

I have an implementation about this proposal at [here](https://github.com/gyson/shan).

It also includes a few simple promise-based middleware (e.g. router).

**Comment by thelinuxlich** [comment]
Great proposal! You should mention that your benchmarks are already using Bluebird as Promise polyfill, if it were with co it would be even slower.

**Comment by thelinuxlich** [comment]
I have no problem with the extra typing, I think it can help new Koa users because of less "black magic" :)

**Comment by gyson** [comment]
yea. `yield next` really confused me until I dig into source code. I think `next(ctx)` is a more common API.

**Comment by fengmk2** [comment]
If these are two types of middlewares, you need to tell developers 'When should I use Promise-style or Generator-style?'.

koa `this` meaning ctx, and promise-style need to pass ctx in the first argument.
This change is not the koa style.

Emtpy middleware like `next(ctx)` or `yield next` meaning nothing.

In the real world, the application performance almost depend on you backend services, not the application itself.

**Comment by tj** [comment]
I prefer our current use of `this` as the context personally but the rest sounds fine at a glance!

**Comment by gyson** [comment]
@fengmk2 

* Ideally, Promise-style should always be preferred. Supporting Generator-style is for backwards compatible and seamless migration.

* I prefer to use context as first argument for supporting arrow function and async arrow function, but I am ok about using `this` as context.

* Why benchmark with empty middleware meaning nothing? How are you going to do the benchmark?

**Comment by jonathanong** [comment]
> I prefer to use `context` as first argument for supporting arrow function and async arrow function, but I am ok about using this as context.

never thought about that. that's a pretty good argument to do `async (context, next) => next()`

**Comment by calebboyd** [comment]
Ironically, this is what I was gunning for 6 months ago...https://github.com/calebboyd/app-builder

**Comment by thelinuxlich** [comment]
Hope this happens, it's not so verbose

**Comment by tj** [comment]
Oh right => retains the receiver; getting rusty haha. Hmm yea tough call, I definitely like `this` a bit better since you really don't need nesting in middleware/routes (or if you do you're probably not abstracting things properly)

**Comment by thelinuxlich** [comment]
You can swap the context in this case(although I don't know if this is useful lol)

**Comment by gyson** [comment]
According to @tj 's suggestion, I made two changes to my previous proposal:

* change to use `this` as context
* change from `await next(context)` to `await next()` because I think `await next(this)` is a little bit annoy and error prone (scope of this). This results a very little penalty on benchmark because it needs to create some extra closures.

With these changes, it's still Promise-based, backwards compatible and performance improved for non-async case.

I am also amazed that this API is basically what @calebboyd proposed at the very beginning. :+1: 

Then the code sample would like this:

```js
app.use(function (next) {
  // before
  return next().then(() => {
    // after
  })
})

app.use(async function (next) {
  // before
  await next()
  // after
}) 
```

Some [numbers](https://github.com/gyson/koa-benchmarks/tree/63260162ac8017e50b469a3ffb65012e0b755279) if you are curious:

| API | 1 | 25 | 50 | 75 | 100 |
|:----|--:|---:|---:|---:|----:|
| `return yield next` | 9210.96 | 5186.64 | 3780.56 | 2829.59 | 2209.87 |
| `return next()` | 10084.17 | 9995.48 | 9675.06 | 9462.32 | 9313.42 |

Any thoughts? Does it look better?

**Comment by thelinuxlich** [comment]
yes plz :100:

**Comment by tj** [comment]
nice :D

**Comment by ruimarinho** [comment]
This looks really good! Nice work.

```js
app.use(async next => {
  await next()
});
```

**Comment by jonathanong** [comment]
@ruimarinho i don't believe that'll work because `this` isn't passed into the `=>` function.

**Comment by ruimarinho** [comment]
Hmm, it did, because I've just tested it with `koa-next-as-function/async-await.js`.

**Comment by tj** [comment]
Ah boo I was thinking it was just lexically bound by default, couldn't remember, guess not. Maybe passing ctx is the way to go then. Need a skinny arrow :( moar ES features

**Comment by ide** [comment]
One thing I like about passing `ctx` around is that it frees up `this` so that your middleware can be an object's method like this:

```js
class KoaResponseCompressor {
  constructor(options) { ... }
  async compressResponseAsync(ctx, next) {
    await next(ctx);
    ...
    this.helperMethod();
    ...
  }
  helperMethod() { ... }
}

export default function middleware(options) {
  return ::new KoaResponseCompressor(options).compressResponseAsync;
}
```
```js
import responseCompressor from 'koa-response-compressor';
app.use(responseCompressor(options));
```

**Comment by tj** [comment]
@ide good point. It's definitely the more elegant solution, arg or not. Only other alternative I can think of at the moment (which I don't like haha) is hanging it off `ctx.next`

**Comment by calebboyd** [comment]
Currently `async/await` (to generator) won't work with anything but transpiled arrow functions. There is no such thing as a GeneratorArrowFunction. But there is a proposal for the AsyncArrowFunction.  

Because of that, you can't use native `=>` from Node 4 unless you opt in to using slower regenerator transformations. See issue here: [babel/babel#2342](https://github.com/babel/babel/issues/2342)

@tj, The composing function I set up implements both of those options
https://github.com/calebboyd/app-builder/blob/master/index.src.js#L13-L14

**Comment by mpal9000** [comment]
+1 for passing ctx as an argument:
- more functional, more flexible
- problems in this discussion
- closer to page.js, ie. easier to create a more portable/isomorphic solution
- closer to express, ie. easier adoption

For me koa with a more functional style (this change and maybe without prototypes) and async functions will be close to perfection :P

**Comment by gyson** [comment]
Just realized that using ctx as argument would work very nice with destructuring.

```js
app.use(async ({request, response}, next) => {
  // ...
  await next()
  // ...
})
```

Not sure if this is really useful, but worth sharing.

**Comment by jonathanong** [comment]
https://github.com/koajs/compose/pull/27 if anyone wants to check it out

**Comment by smcmurray** [comment]
What's the strategy to create compatibility with existing middleware that doesn't expect a context as an argument?

**Comment by hiroqn** [comment]
For the compatibility, 
when passing ctx as arguments, second arguments is better.
And at the same time, bind this for ctx.

And when using non-GeneratorFunction, next is instance of  Promise is easy to understand, i feel.

```
app.use(function *(next) {
  this.body += ':b';
  yield next;
})

app.use(async (next, ctx) => {
  ctx.body += ':D';
  await next;
});

app.use(async function(next) => {
  this.body += ':)';
  await next;
});

app.use((next, ctx) => {
  ctx.body += ':D';
  return next;
});

app.use(function(next) => {
  this.body += ':)';
  return next;
});

```

**Comment by smcmurray** [comment]
@hiroqn , the argument order is set. Context is passed first because it is required and next is optional. Not binding to this allows comments like @ide's above.

As for making next a promise, next is a middleware function. It has to be invoked. Your examples never invoke next. Indeed, they seem to rely on the next middleware having already been invoked. This doesn't makes sense.

return next(ctx);

This will still return a promise.

**Comment by felixfbecker** [comment]
I really think the concept of _calling_ the next middleware function explicitly and _awaiting_ it's promise is much easier to understand for newcomers than _yielding_ next without calling.
Also, I think it should simplify unit testing of middleware.
So, what is the ETA for this? Can I help out somehow?

**Comment by smcmurray** [comment]
@jonathanong, can koajs/compose/#27 wrap up into some pre-release version right away and then provide a koa pre-release branch that uses the koa-compose pre-release?

Having this available ASAP would help it mature into something releasable.

**Comment by ruimarinho** [comment]
@smcmurray @jonathanong what about releasing it as 3.0.0-alpha on npm?

**Comment by mike-marcacci** [comment]
I would be very happy about a 3.0.0-alpha release of this right now: I'm setting up the foundation for a project that won't see production for a little bit but needs to build developer consensus sooner rather than later.

I'm a pretty big fan of this proposal, so I'd love to start out in this direction!

**Comment by thelinuxlich** [comment]
Once it ships I'm using it!

**Comment by jonathanong** [comment]
please test this! https://github.com/koajs/koa/pull/530

**Comment by Globik** [comment]
Is still there a ctx.state?

**Comment by jonathanong** [comment]
not related to es7 async functions. if there isn't, you could always do `this.state = this.state || {};`. can you open a new issue?
