### ISSUE TITLE
How use assets in koajs?

### ISSUE THREAD

**Issue by Fudoshiki** [koajs/koa#439]
How can I use client assets in koajs with minification and digests in slim templates

**Comment by bucaran** [comment]
What are client assets? Do you mean CSS, HTML, and stuff like that?

What do you mean by digests?

What are slim templates?

**Comment by Fudoshiki** [comment]
Sorry, I have jade html templates, client side css and js files, i want precompile them with minification and fingerprinting(digests) in one css and js file like http://guides.rubyonrails.org/asset_pipeline.html

**Comment by hallas** [comment]
@Fudoshiki 

If you want to precompile resources then you would probably sync them with a CDN of sorts in a separate buildstep. Then you should version them an save the versions in a manifest. Then you can use the correct static resources as you deploy your application on your servers.

Pre compiling the Jade templates and having them served as static resources only makes sense if your app is completely clientside.

If it serverside you can compile the jade statements once when your app starts instead of compiling them on every request. I guess the same makes sense for CSS preprocessors but it's just not sensible to serve them via Koa because it's an unnecessary expense of server resources that should be spent computing business logic.

**Comment by hallas** [comment]
Koa does not offer any an asset pipeline out of the box per se. I don't know if anyone has created it, but I don't see why anyone would. For this I would setup grunt or gulp and go about it that way. You can find plenty of articles online on how to do that.

**Comment by Fudoshiki** [comment]
thank you, i will try with grunt/gulp
