### ISSUE TITLE
context.is  or request.is return null

### ISSUE THREAD

**Issue by zppro** [koajs/koa#440]
nodejs v0.12.2
koa v0.20.0
...
app.use(function *(next){
    if(this.request.is('application/json')||this.is('json')){
        // Query
        var builder = sqlBuilder();

        var request = builder().request(); // or: var request = connection.request();

        yield request.query('select * from Pub_User', function(err, recordset) {
            // ... error checks

            //console.log('check user '+JSON.stringify(recordset));
            console.log('get recordset');
            _self.message = 'hello';

        });
        console.log('check user');
    }
    yield next;
});
,,,

so ,    if(this.request.is('application/json')||this.is('json')){ 
is not work ,it return null
but in fidder the request header is 

GET http://192.168.1.165:3000/ HTTP/1.1
User-Agent: Fiddler
Content-Type: application/json
Host: 192.168.1.165:3000

why?

**Comment by tj** [comment]
looks ok to me if that really is the request at the bottom there, can you reproduce with a small script or in a test?

**Comment by dougwilson** [comment]
Your request actually needs body content. Having body content would mean you should have a Transfer-Encoding header or a Content-Length header, which you are missing.

If you are not trying to parse a body, you should instead use the Accept request header and this.request.accepts('json').

**Comment by zppro** [comment]
this.request.accepts('json')  works!
and add content-length:0 also works!!

**Comment by zppro** [comment]
this.request.accepts('json') works!
and add content-length:0 also works!!

**Comment by tj** [comment]
oh yea hahaha good call, missed that

**Comment by yanickrochon** [comment]
I have this problem with koa@1.1.2.

The request is sent via jQuery : `$.getJSON('/url/');`

and `this.is('text');` and `this.request.is('text');` always returns `null`. Also, `this.accepts('html');` returns `html`.

The request looks like this

![selection_037](https://cloud.githubusercontent.com/assets/78461/11822901/01548524-a33f-11e5-9954-657104bbb731.png)

**Comment by dougwilson** [comment]
Hi @yanickrochon there is nothing with those response, as both are correct:

1. `.is('text')` is `null` because your request is a GET request; it has no body, so the request is nothing.
2. `.accepts('html')` returns `html` because yes, the browser accepts `html/text`, as the `Accept` header includes `*/*`, which means it'll accept anything.

**Comment by yanickrochon** [comment]
@dougwilson hmm... alright for `this.is(...)`, except that it still does not honor the documentation, where it should return `undefined`, not `null` (docs should be updated in any case), and I don't understand why a body is required since `content-type` is sent anyhow?

As for `this.accepts(...)`, there should be a strict option that ignores wildcard and return only explicit accepted values. Something like `this.accepts('html', true);`. This would make things more easier to test as I don't want to manually test all other content types, simply because `html` can match `*/*` in every cases, even if totally irrelevant.

**Comment by dougwilson** [comment]
> except that it still does not honor the documentation, where it should return undefined, not null (docs should be updated in any case)

Make a documentation pull request :) You never mentioned anything about the doc irregularity in your original post, sorry.

> and I don't understand why a body is required since content-type is sent anyhow?

You have no `Content-Type` on the request in your example, only in the response. You are calling `.is` on request, not response, thus the method is explaining to you properties of the request (`this.is` is just a shortcut to `this.request.is`)

> As for this.accepts(...), there should be a strict option that ignores wildcard and return only explicit accepted values. Something like this.accepts('html', true);. This would make things more easier to test as I don't want to manually test all other content types, simply because html can match */* in every cases, even if totally irrelevant.

Please open a new issue with your proposal for discussion, and it can certainly be discussed. I didn't see you make any mention in your original post regarding this proposal, sorry. SInce you were posted in an existing issue, I could only assume you were posting something related to the original issue in this thread and not something off-topic, I'm sorry.

Please create new issues for the various things.
