### ISSUE TITLE
Semantic release

### ISSUE THREAD

**Issue by stojanovic** [koajs/koa#523]
Since Koa is now using semver, it's probably a good idea to consider using [semantic-release](https://github.com/semantic-release/semantic-release) too.

What would Koa get with it:
- Automatic semver control
- Release changelog
- Break detection
- Automatic npm release

What's need to be updated:
- Installing semantic-release (one time only, and it's simple)
- Improving commit messages so they can work with semantic-release and changelog generator

It supports updating old releases too, ie. Koa is on 2.x and you want to update 1.x with some important update.

Also, another there's another cool tool that can be used with Koa: [greenkeeper.io](http://greenkeeper.io)

**Comment by tejasmanohar** [comment]
:+1: for [semantic-release](https://github.com/semantic-release/semantic-release)

**Comment by jonathanong** [comment]
i do wanna setup greenkeeper. i'd need to look more into semantic-release

**Comment by stojanovic** [comment]
If you need more info ping me.
Both are really good tools.

**Comment by pensierinmusica** [comment]
+1 for having a changelog

**Comment by tj** [comment]
@pensierinmusica we have always had one https://github.com/koajs/koa/blob/master/History.md

**Comment by pensierinmusica** [comment]
Thanks @tj! Where do I find changelog and usage information for Koa v2.x?

**Comment by tj** [comment]
I think the 2.x was moved back into a separate branch instead of master https://github.com/koajs/koa/blob/v2.x/History.md

**Comment by pensierinmusica** [comment]
Is there any explanation I can find about:

- What is being changed from 1.x to 2.x, why, and what is the performance difference
- How 2.x works
- What are best practices to convert from 1.x to 2.x
- What modules support 2.x

Thanks!

**Comment by tj** [comment]
Good question! I haven't seen any migration docs around but the new Readme sort of highlights the change. It's not obvious that its the only thing that changed but basically just the middleware signature:

https://github.com/koajs/koa/tree/v2.x#example

Which was made because async/await effectively replaces generators, which was actually our intent from the very beginning, but generators were the first thing enabling a similar experience.

https://github.com/koajs/koa/tree/v2.x#example-with-async-functions-babel-required

**Comment by jonathanong** [comment]
i don't think it's worth setting up and having everyone follow the rules. publishing also takes 5 seconds and happens once every few months. it's not something that needs to be optimized.
