### ISSUE TITLE
Where does maintainer discussion of Koa happen?

### ISSUE THREAD

**Issue by kraghack** [koajs/koa#580]
Koa v2.0 is a heavy evolution from v1.x. At a glance, I gather that it's trying to be more general/versatile so that it can gracefully handle both async/await (Babel compilation) and the generator abstraction of v1.x, and one of the ways it is achieving this is to drop the dependency on `co` and aim for a middleground with promises.

However, I'd be interested to either follow the discussion that drives these decisions or be illuminated on the high-level goals that drive these changes.

I traversed the /issues to see if this discussion was simply scattered, but it's as if everyone has agreed on the goals already and the /issues are just relegated for more trivial implementation details.

You guys are doing a good job and for all I care all decisions are made at a weekly meeting at the bar. I'm just trying to develop an understanding of Koa's endgame goals, why v2.0 is the way that it is, and what we can expect in the future.

**Comment by tj** [comment]
2.x is still open to changes but the general aim is to remove some of the magic introduced with generators, since that was all we could rely on at the time, with async/await of course being the "real" solution. If you have any feedback before 2.0 is cut definitely chime in!

As far as the discussion goes it's definitely scattered :D, open to suggestions there, I believe we have a mailing list but I've honestly always just used Github issues. GH issues might be fine if we have nicer titles and keep everything in a single issue etc.

**Comment by kraghack** [comment]
Alright, so it really is just scattered/wandering.

The mailing list is inactive, but that's pretty normal for a framework that's not Rails. Looks to me like GH issues are the best place for discussion even if it's scattered — it's where the devs already are.

I will just be more proactive about asking questions as I have them. Thanks.

**Comment by kriswill** [comment]
@kraghack There's also: [![gitter][gitter-image]][gitter-url]

[gitter-image]: https://badges.gitter.im/Join%20Chat.svg
[gitter-url]: https://gitter.im/koajs/koa?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by yanickrochon** [comment]
If you "watch" the repository, and be notified by e-mail about changes, you can discard issues that are of less interest to you and follow discussions on others. This is how I am keeping up to date with Koa (and I think I was the first to propose the removal of `co`... so... :P ).
