### ISSUE TITLE
Best practice for async with Koa 2.0

### ISSUE THREAD

**Issue by derek-duncan** [koajs/koa#581]
First off, Koa 2.0 –> great work! I've been playing with it today and have really appreciated the focus on modularity and the future of js.

In light of this new release, what's the most preferred/best practice for handling *asynchronous operations*? In previous iterations of Koa, generators have been exclusively used to provide handle async and avoid callback hell. With this new release, generator support has been completely dropped in preference of async functions, which rely heavily on Promises.

Anyways, I'm often posed with the challenge of choosing one of the above options to handle asynchronous operations. However, I want to generally keep my choice consistent across a codebase since generators and async functions seem to not work fluently together. Also, as a personal preference, I'd like to avoid wrapping so many functions/modules in a helper function (like `koa-convert`) in lieu of forcing these various options to work together. Thus, I just wanted to hear the Koa community's thoughts on the matter before I go dive into an unconventional direction.

**Comment by felixfbecker** [comment]
- If you don't mind transpiling, use async/await with Babel
 - If you want the beauty of async/await without transpiling, use co.wrap or Bluebird's coroutine with yield instead of await (this is what I do, but if you have coworkers it's a bit harder to explain).
 - If you don't want to use generators or transpile, just return a promise in your middleware and chain it for your async operations.

For modules that don't return promises, promisify with Bluebird - it means you don't depend on wrapper modules that might not be always up to date.

koa-convert is mainly to convert from the old _signature_ of `this` as context to `(ctx, next) => ...`.

I hope this helped :)

**Comment by tejasmanohar** [comment]
:+1: - @felixfbecker's comment (more or less) should be in one of our docs

**Comment by felixfbecker** [comment]
Maybe we should simply add some async database operations to the existing examples in the docs for asyncawait/promise/generator so it's clearer how to combine them?

**Comment by felixfbecker** [comment]
Oh and of course you can construct your own promise if you're working with a very EventEmitter-heavy library which are tough to promisify (ldapjs as an example):
```js
app.use((ctx, next) => new Promise((resolve, reject) => {
  ldap.search('dn=users', (err, result) => {
    if (err) return reject(err)
    result.on('searchEntry', entry => {
      ctx.body = entry.object
      resolve()
    })
    result.on('error', reject)
  })
})

**Comment by yanickrochon** [comment]
At the beginning of Koa, it is of my understanding that `co` was used (i.e. using `yield` with generators) to facilitate using asynchronous functions and thus eliminate callback hell. This was a solution in place of relying on Bluebird and such, which are heavy on dependencies; in short, this was for a simple but hacky solution as generators are not inherently asynchronous but made so via `co`. The consequence, then, was ugly stack traces and an inevitability of always using generator functions even when coding sync'ed middlewares. Later on, a `Promise` prototype was officially implemented natively, but offered very poor performances compared to existing libraries like Bluebird. Then IO.js and, later on, the release of Node 4.0 came along to greatly improve on native promises (with added functionalities), so motivated some refactor in Koa.

RIght now, the general consensus is in favor of using promises in middlewares since they integrate well with synchronous as well as asynchronous code (as @felixfbecker demonstrated) and they do play well with error handlers with clear stack traces. Or you can use a transpiler with async/await, which are very likely to be implemented natively as well at some point with very little differences (if not at all) from current implementations thereof.

So, the decision to officially drop `co` and generators is to favor better usage of sync/async usage without requiring wrapping code in generators, or forcing using generators because somewhere down the call stack, a generator function is being used.

With Koa < 2, @felixfbecker 's example would look like this :

```
app.use(function () {
  var ctx = this;

  return function (done) {
    ldap.search('dn=users', {filter: 'cn=waldo'}, function (err, result) {
      if (err) return done(err);
      result.on('searchEntry', function (entry) {
        ctx.body = entry.object;
        done();
      });
      result.on('error', done);
    });
  };
});
```

which is not even using a generator, but does wrap the code in an extra function... and note that `next` is not used? How would it be yielded, then? You'd need to create yet another wrapper just for that :

```
co.wrap(function * () { yield next; }).then(done).catch(done);
```

**Comment by felixfbecker** [comment]
@yanickrochon just a couple of things:
 - Bluebird has zero dependencies.
 - In your very last example of calling next, it is even easier, you just have to do `resolve(next())`, as resolving with a promise will make the initial promise adopt that promise.

**Comment by yanickrochon** [comment]
Well, I stand corrected on Bluebird. I must have mixed another project having `lodash` for dependency then. I never really used Bluebird... :/

**Comment by tj** [comment]
Yea Co was just for the use of generators, nothing to do with Bluebird, I'm not positive but pretty sure Bluebird's coroutine stuff came later.

Personally I think any written promise directly inside of a route is too much, that's just an indication that it should be broken out into a lib. All you should be doing really is await-ing things.

**Comment by yanickrochon** [comment]
@tj I agree. AFAIC the example is merely what it is; an example. Routes (or controllers) should be as thin as possible.

**Comment by aheckmann** [comment]
I disagree with the view that Promises are better. I hit extreemly hard to debug issues with Promises in production apps and our team now avoids them due to lack of productivity involved with tracking this stuff down. 

We specifically used koa to get the beautiful, easy to understand syntax of generators. Of course it isn't a first class lang feature but the resulting code clarity is worth its weight in gold.

If generators are out of koa, I'll likely be forking koa 1 to continue maintenance of it.

**Comment by jonathanong** [comment]
you don't have to fork it... we're gonna maintain 1.x for a while

**Comment by aheckmann** [comment]
How long is "a while"?

**Comment by jonathanong** [comment]
until at least async/await is native.

**Comment by tj** [comment]
I think it's sort of more of a language problem in general. Without having full coroutines like Go it'll always be sort of sketchy and awkward to debug, multiple paradigms doesn't mix well, but supporting the one that is built into the language is a bit more elegant than the generator hack at least

**Comment by tejasmanohar** [comment]
> it'll always be sort of sketchy and awkward to debug, multiple paradigms doesn't mix well
Agreed, @tj. For example, `await` is not a keyword, will never error when you `await` a non-Promise, etc... it will always feel slightly unnatural / foreign to deal w/ values serially yet asynchronously in JS.

**Comment by tj** [comment]
It's pretty much a hack at best until node uses promises all the way down, until then there will still be errors off the stack from streams and some funky parts of the stdlib that just throw (favouring that over multiple callbacks I guess?). The further promises are pushed down the better, but event loop + error handling just doesn't really work in general haha, you have to choose swallowing errors or multiple callbacks + undefined behaviour

**Comment by tejasmanohar** [comment]
Right, I still think it's better than callbacks.

**Comment by felixfbecker** [comment]
I also like a lot what you can do when setting BLUEBIRD_DEBUG=1 (It will be nice once we get something like this in core). You get "possibly unhandled rejection" notices, "a promise was created but none returned", and long stack trances ("from previous event"), so you finally know who triggered the async operation. I guess we don't have to discuss the beauty of promises and coroutines.

**Comment by aheckmann** [comment]
Cool, thanks for the info everyone!

**Comment by romeovs** [comment]
@jonathanlong excuse me if this is a silly suggestion because I'm not familiar with the internals of koa (and probably lack some understanding about generators as well) but in my head the difference between 1.x and 2.x seems just a superficial one (a wrap with `koa-convert` can translate it, with some exceptions).

when writing code for the 1.x api I was always mentally picturing the async/await syntax: translate `await` to `yield` and move on.

So here's the suggestion/question (suggquestion?): since most if not all of the functionality between 1.x and 2.x should be the same, couldn't we factor that out into a different module upon which koa 1.x and 2.x depend, but externalise a different api? 

This way koa 1.x and 2.x could just be different adaptors for the same core functionality (`koa-core`) and would likely need to change very little, sparing us the cost of maintaining two versions.

**Comment by felixfbecker** [comment]
@romeovs trading the cost of maintaining two versions for the cost of maintaining an extra repo plus 2 seperate adapters?

The point in koa2 is that in koa1 `yield` could not be replaced by `await`. `await` awaits a promise. But `next` is not a promise, but the next middleware. `next()` is a promise. Therefor, in koa 2, you actually _call_ the next middleware and _await_ it's promise, while in koa1 it was kind of magic what koa did with the `yield`.

The second thing is context as argument, which allows object methods to be middleware and arrow function middleware.

There is really no point in having the old style as a sperate adapter if the new style is objectively superior.

**Comment by romeovs** [comment]
I agree with the fact that the new api has a lot less magic in it, and for that reason alone is already much better in my eyes. 

It *is* objectively superior. 

I was just thinking out loud there because there seems to be demand for keeping the old api alive for a while. The cost of maintaining the two adapters should be very low since they'd hardly ever need to change. But you're probably (certainly) right that is complicating things too much. Forget what I was saying!

**Comment by yanickrochon** [comment]
@romeovs keep in mind that breaking BC is necessary here. Of course there will be some who will be upset about it, and there's really no reason why they should be. As it was said, the `1.x` branch will still be around for a while, be maintained and all. To me, all these conversations about keeping BC is nothing but frivolous. Koa 1.x still work just fine under Node 4.x... And the new interface simply embrace more fully Promises and new features for all the reasons previously explained. Beyond that, there's no significant change in functionality over the previous version. So, for those who don't want, or can't afford to refactor, talking about keeping `yield` within koa's responsibility is silly and counterproductive. Besides, some issues are still to be resolved, notably compositing, so it is not the time yet to upgrade in production.

**Comment by romeovs** [comment]
@yanickrochon agreed. I was just speculating on the train! Sorry if I was to frivolous. I really do like the new api better and I'm using it in some small setups already!

**Comment by yanickrochon** [comment]
@romeovs nothing personal :) I was also addressing anyone who might think that way too. Cheers!

**Comment by romeovs** [comment]
@yanickrochon oh no offense taken 😊keep up the good work :+1:

**Comment by jonathanong** [comment]
merging this into https://github.com/koajs/koa/issues/533. let me know if you have any more questions :)
