### ISSUE TITLE
Setting up project/development environment - Guide

### ISSUE THREAD

**Issue by oeb25** [koajs/koa#604]
With the release of babel 6 and koas move to 2, I haven't been able to find the appropriate `.babelrc` setup, whether to use `babel-node` or precompilling.

All in all, I think it might be hard for people to start using koa, with the extra babel boilerplate that 6.x added. A guide would be very much appreciated.

**Comment by mattstyles** [comment]
[Theres an issue](https://github.com/koajs/koa/issues/596) detailing suggested babel presets/plugins, note that if you're only after the koa2 async stuff you only need an async plugin to transpile.

Using `babel-node` is probably a no-no in production.

As for a detailed guide, I'd probably wane against an officially supported one. Koa2 is only ready as a kind-of dev-preview, due to issues like requiring a transpile. A how-to guide encourages people who dont really know whats going on to get up and running, with stable stuff thats fine, but for active dev stuff thats probably a dangerous move.

v1 is still the *stable* version, the branches are going to go through a quick jiggle so that that becomes obvious again.

**Comment by tejasmanohar** [comment]
The only suggested method of using Babel in production is transpiling.

**Comment by jonathanong** [comment]
merging this issue into https://github.com/koajs/koa/issues/596
