### ISSUE TITLE
KOA 2.0 Status

### ISSUE THREAD

**Issue by amcdnl** [koajs/koa#631]
I'm new to KOA and very excited to start working with it.  I see a LOT of people talking about KOA2 but i look at the milestones and it says its only 35% done. 

Question is: Should i be starting on KOA2 since this is a new project? How 'stable' is it if I were to go into a production in ~3months? Does middleware port easily from 1.x?

I'm using babel with advanced features like decorators and async/await so it kinda seemed like KOA2 was the way to go but was just curious on the above. Thanks!

**Comment by fl0w** [comment]
koa@2 is, as far as I understand it, not going to be released until async/await is implemented in node. 

There's a few things to await (no pun intended) before this happens. The spec needs to be [finalised](https://github.com/tc39/ecmascript-asyncawait) (currently stage 3), [v8](https://bugs.chromium.org/p/v8/issues/detail?id=4483) needs to implement it, and node needs to catchup and make a release.

1. I don't think this is going to happen in 3 months.
2. I don't think it's to develop a new application using koa@2. If you know what's up.
3. I don't think it's wrong develop a new application using koa@1 with generators.

**Comment by amcdnl** [comment]
@fl0w Thanks for the feedback! I'm worried about it not being implemented til ES7 is done since Node has limited ES6 support right now.

We are using Babel already ( side note: debugging has been pretty shakey for me with Babel6 + Node ) so I might as well roll with K2. In terms of stability and legacy middleware support, how is that?

**Comment by divmgl** [comment]
I would say use Koa 1 with generators. It's relatively safe for production. With 2.0 you may run into issues where things change or break and transpiling adds another tier of headaches.

**Comment by leobudima** [comment]
I'm in a similar position to @amcdnl - really excited about porting our existing app to Koa, but reading all the stuff here about 2.0 makes it hard for new people to decide to pick up the framework for a serious project. For a new project, it's weird to be expected to go with 1.x when there are so many mentions of 2.0.

I see a couple of points (just friendly suggestions, of course) that could maybe be improved upon to make it more clear to everyone new coming aboard:

* figure out a roadmap - it's hard to decide to invest time into a framework if there is no solid path forward, at least for the near future

* I agree with @tj on https://github.com/koajs/koa/issues/533 - no point in rushing if it doesn't bring anything new - but a new release SHOULD bring new stuff and excite people about using it, and also show them that there is progress and thought behind the continued framework development!

* when 2.0 is tied to the roadmap, mention 2.0 on the website - so it gives people straightforward information on when it's coming, what it will bring and, if they're starting a new project, what should they use. If the recommendation is 1.x, then what will the eventual upgrade entail.

I think it's perfectly fine to push 1.x for newcomers, if only info on 2.0 would be more clear and explained what the eventual upgrade will require. So that I can decide to go with Koa now, knowing that I'm not going to waste time since in 3 months I'll need to redo a lot or remain stuck on old version when new one is released. And it's weird to say it's fine, since new version doesn't bring anything anyway :)

Just my 2 cents, from an outside perspective - sorry for the long text! :)

**Comment by divmgl** [comment]
From what I can tell, the only mention of 2.0 is in the issue log so it would be nice to warn newcomers. It looks like 2.0 is still quite a few months away as we wait for the V8 to have native `async`/`await`. 

Hold off on porting your existing app over @leobudima, especially if it doesn't have any existing problems. You're going to want to upgrade your app anyways once 2.0 is stable.

**Comment by kievechua** [comment]
Is Koa 2 support http 2? Or I can using node-spdy as is?

**Comment by yanickrochon** [comment]
@kievechua AFAIK, HTTP2 will be implemented by Node itself, through the built-in `http` module. This is not Koa's responsibility to implement a protocol layer; Koa is at the application layer.

**Comment by pensierinmusica** [comment]
@tj, in https://github.com/koajs/koa/issues/625#issuecomment-166201819 you mentioned: 
> just that we have something available for when Node gets async/await.

Any idea when that is going to happen? Is there any timeline, or approximate date, for Node / V8 to implement native async functions?

Thanks, cheers!

Relates #621

**Comment by fl0w** [comment]
@pensierinmusica ES7 (or ES2016) is expected this year, I'm unaware of a specific target date. I'd guess  around or after finalisation of the spec. Google might introduce async/await earlier in V8, but that wouldn't be official and it would probably be hidden behind a flag in that case.

**Comment by kievechua** [comment]
@yanickrochon I though Koa 2 changes break the compatibility with node-spdy/node-http2, just stupid me not using https in localhost ...

**Comment by lourd** [comment]
You're not stupid, that's just programming =) you just reminded 500 people of a mistake they may make.

Also [here is the Chromium issue](https://bugs.chromium.org/p/v8/issues/detail?id=4483) for adding async/await into v8.

**Comment by vinerz** [comment]
How long will be koa 1.x be maintained after the 2.0 release? I am afraid to start my project with a deprecated library

**Comment by tj** [comment]
@vinerz I wouldn't worry about it too much, mostly because the upgrade path will basically be a find/replace, but due to that maintaining 1.x should be easy for us to do for quite a while as well

**Comment by vinerz** [comment]
That sounds awesome. Thank you!

**Comment by danneu** [comment]
An unfortunate result of koa's limbo between 1.x and 2 is that it's a crapshoot whether the latest stable version of a given library (middleware) works with stable koa vs unreleased koa.

**Comment by jonathanong** [comment]
Latest stable of any middleware should always relate to the latest stable of koa (v1). If it doesn't, let us know and we'll fix it.

**Comment by jonathanong** [comment]
i've updated the description in https://github.com/koajs/koa/issues/533. i will be closing this issue - any future convos should be in that issue!
