### ISSUE TITLE
register multi middlewares

### ISSUE THREAD

**Issue by dominhhai** [koajs/koa#717]
Can multi middlewares be added in one call? 
E.x:

```javascript
app.uses(middleware1, middleware2)
// or
app.uses([middleware1, middleware2])
```

Implement this is not hard, thought.

**Comment by fl0w** [comment]
@dominhhai No, it's 1 mw. However, you can use compose.
```js
const compose = require('koa-compose')
app.use(compose([mw1, mw2]))
```

**Comment by dominhhai** [comment]
Is it possible to add a new method that can register multi-mws?

**Comment by fl0w** [comment]
I guess, I'm not sure about the benefits though. I'm not at liberty to decide on features. Label this issue as enchancement.

**Comment by juliangruber** [comment]
Yeah it wouldn't be hard to add this feature, just a couple lines of code, tests and documentation.

But there's multiple reasons not to:

- the signature `app.use(fn)` is a lot simpler to reason about than `app.use(...fn)`, it does one thing and one thing only
- as far as I'm aware no one besides you has requested this feature yet, and I don't see that being simply because no one has thought of it before. So there isn't enough demand to justify this addition.
- What looks more tidy?

```js
app.use(foo);
app.use(bar(baz));
app.use(beep({
  boop: 'yes'
}));
app.use(another);

// vs

app.use(foo, bar(baz), beep({
  boop: 'yes'
}), another);
```

Single argument `app.use()` helps shape a good style.

- although this change would be tiny, if we say yes to every minor addition, koa will be bloated in no time
- it's trivial to implement this feature in user land:

```js
const use = (app, ...fns) => { for (let fn of fns) app.use(fn) };

use(app, foo, bar(baz), /* ... */);
```

So -1 from me.

**Comment by dominhhai** [comment]
(y) thank for you comment. 
Do one thing only is better!
So, I will close this request.

**Comment by nswbmw** [comment]
@dominhhai You may need [koa-use](https://www.npmjs.com/package/koa-use) :)

**Comment by dominhhai** [comment]
@nswbmw Thanks for your suggestion.
Btw, [koa-compose](https://github.com/koajs/compose) is not good enough?

**Comment by fl0w** [comment]
@dominhhai koa-use patches Application.use, koa-compose composes/encapsulates middleware. koa-compose is a "native"-dependency of koa (koa uses this package internally)

**Comment by BruceHem** [comment]
Can someone tell me a good reason to use koa compose? Any examples would be helpful

**Comment by dominhhai** [comment]
I prefer koa-compose. I don't want to override any core api. Add new method is ok for me, however.

**Comment by juliangruber** [comment]
I just use `app.use()` and koa-compose if I need to
