### ISSUE TITLE
Potentially confusing wording in website/readme file main page

### ISSUE THREAD

**Issue by Clown-Fox** [koajs/koa#768]
Description given for Koa is: "Expressive HTTP middleware for node.js to make web applications and APIs more enjoyable to write."

Additional information listed:

"Koa is not bundled with any middleware."

This may be confusing to new readers and those for whom English may be a second language. As such, suggest amending to:

"Koa is not bundled with any additional middleware."

**Comment by felixsanz** [comment]
pull request it! :)

**Comment by GranularDetective** [comment]
Give me a few minutes and I'll do it for Clown-Fox. Just need to have a bath first!

**Comment by fl0w** [comment]
Sure, the word `middleware` is ambiguous, and could potentially be misunderstood. However I don't see that adding `additional` to that phrase solves the ambiguity. If anything, I would much rather see a reinterpretation of `HTTP middleware` to `HTTP framework` or something like `abstraction layer on top of node.js HTTP`.

**Comment by GranularDetective** [comment]
You want me to make things more specific! Gotcha :fl0w! I'm getting this! So Clown-Fox was _kind of_ right but so are you, because he was suggesting using the same word for the two different middlewares was a problem and it is. But you are saying it's better to specify exactly what the two middlewares mean rather than just saying "this is middleware a and this is middleware b," as Clown-Fox was.

But there's something I'm still not understanding which is that 'abstraction layer on top of node.js HTTP' seems to be a longer way of writing 'middleware' but I know that's not it.

So.............. maybe, we could call them layers, like with the different security layers. But then, you've already sort of done that with talking about high level *sugar* so...

Hmmmm... I'm stumped at this point...

@Clown-Fox Any more of your bright ideas, Mr The Clown-Fox?

**Comment by juliangruber** [comment]
> But there's something I'm still not understanding which is that 'abstraction layer on top of node.js HTTP' seems to be a longer way of writing 'middleware' but I know that's not it.

koa is an abstraction layer on top of node.js HTTP that uses the concept of middleware for structuring your routes, so it's both.

> This may be confusing to new readers and those for whom English may be a second language. As such, suggest amending to:
> 
> "Koa is not bundled with any additional middleware."

Koa isn't bundled with _any_ middleware, the confusion that's going on here is probably that `Expressive HTTP middleware for node.js` is misunderstood. The more explicit form would be `Expressive HTTP middleware abstraction for node.js`.

I can definitely see how this is confusing. I don't think the first sentence should be changed, but there can be more clarification underneath.

**Comment by tj** [comment]
Reads a little wonky to me too, we also mention middleware again in the next sentence so I'll tweak that a bit

**Comment by tj** [comment]
something like https://github.com/koajs/koa/commit/0590430d7b59c4e7ffdc6df49a6ee1314b0d71ac
