### ISSUE TITLE
[v2.x]Why use `text/plain` content-type for error response?

### ISSUE THREAD

**Issue by dominhhai** [koajs/koa#787]
For Rest APIs, it's better to use `application/json` Content-Type instead of `text/plain` when throw an error with a detail message in `json` type. 
Can anyone explain why Koa uses  `text/plain` for the [default error handler](https://github.com/koajs/koa/blob/v2.x/lib/context.js#L125)?

**Comment by dead-horse** [comment]
see https://github.com/koajs/koa/issues/758

You can write your own error handler, koa's default error handler is just a simplest error handler, in most situation you should write your own to override it.

**Comment by dominhhai** [comment]
thanks for your help.

**Comment by IlyaSemenov** [comment]
This doesn't really answer the question.

For example, I want to to emit a JSON error message from a help function that will be called like this:

```js
app.use(ctx => {
  // here I want to ctx.throw() a JSON response if context is invalid
  const data = validateContext(ctx);
  // proceed with data if context is valid
})
```

This is not currently possible because `onerror` has the following hard-coded:

```
    // force text/plain
    this.type = 'text';
```

Even if I pass `{ headers: { 'content-type': 'application/json' } }` to `createError`, it's overwritten by the above.
