### ISSUE TITLE
unexpected response on stream from stdout

### ISSUE THREAD

**Issue by raminious** [koajs/koa#811]
I need to implement an application to stream stdout into browser

```js
const shell = require('shelljs')
const PassThrough = require('stream').PassThrough

app.use(function* () {

  // in real app, stream generating by another external application
  const command = 'cat ./video.mp4'
  const ch = shell.exec(command, { silent: true, async: true })

  this.set('Content-Disposition', 'attachment')
  this.attachment('video.mp4')

  this.body = ch.stdout.pipe(PassThrough())
})
```

the problem is video size is ~570KB, but downloaded video is ~1MB and can't play that via video players
Is Koa buffer or change the response ? or something else ?

**Comment by raminious** [comment]
Is works:

```js
const spawn = require('child_process').spawn
this.body = spawn('cat', ['./video.mp4']).stdout.pipe(PassThrough())
```

Can somebody tell my why ? 
And what's the difference ?

**Comment by fundon** [comment]
delete `this.set('Content-Disposition', 'attachment')`

**Comment by raminious** [comment]
had no effect @fundon

**Comment by juliangruber** [comment]
since this works with `require('child_process').spawn` but not with `require('shelljs').exec`, I'm assuming this is a shelljs issue. you could try piping the output of shelljs to a file and then see if that plays.

I'm closing because not koa related, but feel free to reopen if you confirm this is actually a koa issue.
