### ISSUE TITLE
eslint rule error: Expected to return a value at the end of this method

### ISSUE THREAD

**Issue by chovy** [koajs/koa#894]
When I define a route handler (ie: post) I get an eslint error: `Expected to return a value at the end of this method`

    async post(ctx){
        ctx.body = { foo: 'bar' };
    }

I'm wondering what the proper way to handle this. Not sure if I should `return ctx` or not.

**Comment by jonathanong** [comment]
disable that rule in your koa app :) 

this is similar to the rule that requires a generator to actually use `yield`, otherwise it's pretty pointless to use a generator at all (except that koa requires it).

for koa v2, you don't have to actually use an `async` function, so you can actually make that function a regular function. however, if you add code, you want to make sure errors are not thrown in a different loop as only the current event loop is try/catched https://github.com/koajs/compose/blob/next/index.js#L44
